## Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0

name: Apache Jena CI
# Manual
on: workflow_dispatch

#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04-ppc64le, ubuntu-latest]
        arch: ['amd64', 'ppc64le']
        exclude:
          - os: ubuntu-22.04-ppc64le
            arch: amd64
          - os: ubuntu-latest
            arch: ppc64le

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        architecture: ${{ matrix.arch }}
        distribution: 'temurin'
        java-version: '17'
    - name: Build with Maven
      run: |

        echo $JAVA_HOME
        echo $MAVEN_HOME
        if [ `arch` == 'ppc64le' ]; then sudo apt-get install maven -y; fi;
        mvn -B --file pom.xml -Dmaven.javadoc.skip=true install
